version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_docker
    environment:
      POSTGRES_DB: marriagebureau
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - postgres

  springboot:
    build: .
    container_name: MarriageBureau
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: marriagebureau
      DB_USER: postgres
      DB_PASSWORD: root
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: temporarydummymail@gmail.com
      EMAIL_PASSWORD: lvhmkjgpddbiqnke
      EMAIL_DOMAIN: temporarydummymail@gmail.com
      CLOUDINARY_API_KEY: 717682729226774
      CLOUDINARY_API_SECRET: L7yhnrUI0SyvUo7E2YLJdW3gK2I
      CLOUDINARY_NAME: dcrlfty5k
    ports:
      - "8282:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: